name: clinic_package
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  dio: ^5.4.3+1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.5
  freezed: ^2.5.2
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: